made some changes

diff --git a/s3/bash-scripts/sync b/s3/bash-scripts/sync
--- a/s3/bash-scripts/sync
+++ b/s3/bash-scripts/sync
@@ -1,1 +1,53 @@
 #!/usr/bin/env bash
+#!/usr/bin/env bash
+
+# exit immediatly if any of the commands return a non-zero status   
+set -e
+
+# Check for bucket name
+if [ -z "$1" ]; then
+    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
+    exit 1
+fi
+
+# Check for Filename prefix
+if [ -z "$2" ]; then
+    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
+    exit 1
+fi
+
+BUCKET_NAME=$1
+FILENAME_PREFIX=$2
+
+# where we'll store these files
+OUTPUT_DIR="/tmp/s3-bash-scripts"
+
+# lets create output folder
+mkdir -p $OUTPUT_DIR
+
+# Clean output_dir if files exist
+if [ "$(ls -A $OUTPUT_DIR)" ]; then
+    rm -rf "$OUTPUT_DIR"/*
+    echo "Output directory cleaned."
+else
+    echo "No files to clean in the output directory."
+fi
+
+# generate a random number
+# to determine how many files to create
+NUM_FILES=$((RANDOM % 6 + 5))
+
+for ((i=1; i<=NUM_FILES; i++)); do
+    # Generate a random filename
+    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"
+    
+    # Generate random data and write it to the file
+    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
+done
+
+tree $OUTPUT_DIR
+
+aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files
+
+
+# usage example ./s3/bash-scripts/sync bucketName fileName
